name: Hello World Workflow

on: push

jobs:
  say-hello:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Print greeting
        run: echo "🎉 Hello from GitHub Actions!"
        run: sudo cp /home/sagar/actions-runner/_work/github-action/github-action/index.html /var/www/html
