name: Hello World Workflow

on: push

jobs:
  say-hello:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Print greeting
        run: echo "🎉 Hello from GitHub Actions!"
